version: '3'
services:
  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160  -max-msg-size=10485760 -broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
  minio1:
    image: minio/minio
    volumes:
      - minio-data1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ahkjfhaejalkdjdfjalkjfa
      MINIO_SECRET_KEY: bvqhubfrqfifbqqibfquifhqiofh
    command: server http://minio{1...4}/export
  minio2:
    image: minio/minio
    volumes:
      - minio-data2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: ahkjfhaejalkdjdfjalkjfa
      MINIO_SECRET_KEY: bvqhubfrqfifbqqibfquifhqiofh
    command: server http://minio{1...4}/export
  minio3:
    image: minio/minio
    volumes:
      - minio-data3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: ahkjfhaejalkdjdfjalkjfa
      MINIO_SECRET_KEY: bvqhubfrqfifbqqibfquifhqiofh
    command: server http://minio{1...4}/export
  minio4:
    image: minio/minio
    volumes:
      - minio-data4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: ahkjfhaejalkdjdfjalkjfa
      MINIO_SECRET_KEY: bvqhubfrqfifbqqibfquifhqiofh
    command: server http://minio{1...4}/export
  zk1:
    image: confluentinc/cp-zookeeper
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  zk2:
    image: confluentinc/cp-zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  zk3:
    image: confluentinc/cp-zookeeper
    ports:
      - "42181:42181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888
  kafka-1:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:9092
  kafka-2:
    image: confluentinc/cp-kafka
    ports:
      - "19092:19092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:19092
  kafka-3:
    image: confluentinc/cp-kafka
    ports:
      - "29092:29092"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: ${MY_IP}:22181,${MY_IP}:32181,${MY_IP}:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MY_IP}:29092

volumes:
  minio-data1:
  minio-data2:
  minio-data3:
  minio-data4:


